### ISSUE TITLE
API | Create host groups fails with message: maximum recursion depth exceeded while getting the str of an object

### ISSUE THREAD

**Issue by BrutalBirdie** [ansible-collections/community.zabbix#1146]
##### SUMMARY
Suddenly the ask  `API | Create host groups` fails with message:
> maximum recursion depth exceeded while getting the str of an object

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

version 2.2.0 of `community.zabbix`

https://github.com/ansible-collections/community.zabbix/blob/870b4e8c919b637f48ff836f5660ee5df0e95406/roles/zabbix_agent/tasks/api.yml#L2-L12

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.1]
config file = /home/eha/develop/gitlab/ansible_plays/ansible.cfg
configured module search path = ['/home/eha/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.11/site-packages/ansible
ansible collection location = /home/eha/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] (/usr/bin/python)
jinja version = 3.1.2
libyaml = True
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/eha/develop/gitlab/ansible_plays/ansible.cfg
DEFAULT_BECOME(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = root
DEFAULT_GATHERING(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = ['/home/eha/develop/gitlab/ansible_plays/inventory/hosts.yaml']
DEFAULT_LOG_PATH(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = /home/eha/develop/gitlab/ansible_plays/log/ansible.log
DEFAULT_MANAGED_STR(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = Ansible managed by brutalbirdie
DEFAULT_ROLES_PATH(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = ['/home/eha/develop/gitlab/ansible_plays/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = /home/eha/develop/gitlab/ansible_plays/scripts/vault_pass.sh
EDITOR(env: EDITOR) = /usr/bin/emacs
HOST_KEY_CHECKING(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/eha/develop/gitlab/ansible_plays/ansible.cfg) = False

```

##### OS / ENVIRONMENT / Zabbix Version

Not relevant since its a local python error.

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

No error . . .

##### ACTUAL RESULTS

```python3
The full traceback is:
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 165, in run
res = self._execute()
^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 605, in _execute
self._handler, module_context = self._get_action_handler_with_module_context(templar=templar)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 1157, in _get_action_handler_with_module_context
socket_path = start_connection(self._play_context, options, self._task._uuid)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 1230, in start_connection
write_to_file_descriptor(master, options)
File "/usr/lib/python3.11/site-packages/ansible/module_utils/connection.py", line 60, in write_to_file_descriptor
src = cPickle.dumps(obj, protocol=0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/copyreg.py", line 77, in _reduce_ex
state = base(self)
^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while getting the str of an object
fatal: [my.openculturas.eu -> monitoring.safeserver.de]: FAILED! => {
"msg": "Unexpected failure during module execution: maximum recursion depth exceeded while getting the str of an object",
"stdout": ""
}
```

The variables for the mentioned task are:
```
host_group: ['cloudron', 'customers', 'customerName', 'services', 'Linux Servers']
```
and
```
state: present
```

I am a bit lost here since it always worked and the variable `zabbix_host_groups` should be a list as it is.
The classic "it worked before" but there is nothing changed in my variables, playbooks yada yada.

Tried to debug a bit:

```python3
    debugFile = open("/tmp/debug.log", "w")
    debugFile.write('Start Debug\n')
    debugFile.write(f"obj is: {obj}\n")
    src = cPickle.dumps(obj, protocol=0)
    debugFile.write(f"{src}\n")
    debugFile.write('End Debug\n')
```
Which never writes `End Debug` to the file so `src = cPickle.dumps(obj, protocol=0)` should be the culprit.

```
Start Debug
obj is: {'host': 'REDACTED', 'port': 443, 'network_os': 'community.zabbix.zabbix', 'remote_user': 'REDACTED', 'password': 'REDACTED', 'session_key': None, 'ca_path': None, 'client_cert': None, 'client_key': None, 'http_agent': None, 'use_ssl': True, 'validate_certs': False, 'use_proxy': True, 'ciphers': None, 'become': True, 'become_method': 'sudo', 'platform_type': None, 'import_modules': True, 'persistent_connect_timeout': 30, 'persistent_command_timeout': 30, 'persistent_log_messages': False, 'zabbix_auth_key': None, 'zabbix_url_path': 'zabbix', 'http_login_user': 'REDACTED', 'http_login_password': 'REDACTED'}
```

and when I try it manually:

```python3
from ansible.module_utils.six.moves import cPickle

var = cPickle.dumps({'host': 'REDACTED', 'port': 443, 'network_os': 'community.zabbix.zabbix', 'remote_user': 'REDACTED', 'password': 'REDACTED', 'session_key': None, 'ca_path': None, 'client_cert': None, 'client_key': None, 'http_agent': None, 'use_ssl': True, 'validate_certs': False, 'use_proxy': True, 'ciphers': None, 'become': True, 'become_method': 'sudo', 'platform_type': None, 'import_modules': True, 'persistent_connect_timeout': 30, 'persistent_command_timeout': 30, 'persistent_log_messages': False, 'zabbix_auth_key': None, 'zabbix_url_path': 'zabbix', 'http_login_user': 'REDACTED', 'http_login_password': 'REDACTED'}, protocol=0)
print(var)
```
No problem.

Thanks for reading my issue and for this awesome collection which I never had issues with so far.

**Comment by mjaepel** [comment]
I have the same issue with community.zabbix.zabbix_proxy.

Cause is a ansible-vault encrypted variable for password/api key. The role works fine if the password/api key variable is unencrypted.
Ansible Vault seems to be working correctly. A debug task for printing the password looks good.

I am not sure if this really related to the collection. There were similar issues with other collections like
https://github.com/ansible-collections/cisco.ios/issues/985
https://github.com/ansible/awx/issues/14689

Maybe an ansible-vault decryption issue with httpapi?

**Comment by BrutalBirdie** [comment]
> I have the same issue with community.zabbix.zabbix_proxy.
> 
> Cause is a ansible-vault encrypted variable for password/api key. The role works fine if the password/api key variable is unencrypted. Ansible Vault seems to be working correctly. A debug task for printing the password looks good.
> 
> I am not sure if this really related to the collection. There were similar issues with other collections like [ansible-collections/cisco.ios#985](https://github.com/ansible-collections/cisco.ios/issues/985) [ansible/awx#14689](https://github.com/ansible/awx/issues/14689)
> 
> Maybe an ansible-vault decryption issue with httpapi?

Ohhh I will check that out! I have many encrypted variables.

**Comment by mjaepel** [comment]
I opened an issue for ansible core: https://github.com/ansible/ansible/issues/82442
And flowerysong had a good solution for me: Update Ansible to 2.16.2 :heart_eyes:

**Comment by BrutalBirdie** [comment]
Thanks, solved by your suggestion. Simply Update :)
