### ISSUE TITLE
Zabbix_server role failling when running with packer

### ISSUE THREAD

**Issue by nosrio** [ansible-collections/community.zabbix#327]
##### SUMMARY
Zabbix server role fails when running using packer on Debian O.S. at TASK [community.zabbix.zabbix_server : apt-get clean]. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_server

##### ANSIBLE VERSION
```
  ansible --version
  ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nosorio/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/nosorio/.local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

  packer --version
  1.6.6
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version
Debian 10

##### STEPS TO REPRODUCE

Run playbook with packer.

```
  # vars/zabbix.yml
  ---
  zabbix_server_version: "5.2"
  zabbix_server_database: mysql
  zabbix_server_database_long: mysql
  zabbix_server_dbport: 3306
  zabbix_server_dbuser: zabbix
  zabbix_server_dbpassword: "{{ mysql_root_password }}"
```

```
- hosts: all
  become: yes
  vars_files:
    - vars/zabbix.yml
  roles:
    - community.zabbix.zabbix_server
```

Packer launch an AWS instance and run this playbook using ansible-local provioner

##### EXPECTED RESULTS

Zabbix installed.

##### ACTUAL RESULTS

Fails at TASK [community.zabbix.zabbix_server : apt-get clean].  
Taking a clcoser look at that task, it executes an "rm -rf /tmp/* deleting packer temporal files.

```paste below
 amazon-ebs: TASK [community.zabbix.zabbix_server : apt-get clean] **************************
    amazon-ebs: task path: /usr/local/lib/python2.7/dist-packages/ansible_collections/community/zabbix/roles/zabbix_server/tasks/Debian.yml:96
    amazon-ebs: <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: admin
    amazon-ebs: <127.0.0.1> EXEC /bin/sh -c 'echo ~admin && sleep 0'
    amazon-ebs: <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/admin/.ansible/tmp `"&& mkdir "` echo /home/admin/.ansible/tmp/ansible-tmp-1613058717.91-11463-153211684994567 `" && echo ansible-tmp-1613058717.91-11463-153211684994567="` echo /home/admin/.ansible/tmp/ansible-tmp-1613058717.91-11463-153211684994567 `" ) && sleep 0'
    amazon-ebs: Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/command.py
    amazon-ebs: <127.0.0.1> PUT /home/admin/.ansible/tmp/ansible-local-4624a8a10y/tmp5Ks5An TO /home/admin/.ansible/tmp/ansible-tmp-1613058717.91-11463-153211684994567/AnsiballZ_command.py
    amazon-ebs: <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/admin/.ansible/tmp/ansible-tmp-1613058717.91-11463-153211684994567/ /home/admin/.ansible/tmp/ansible-tmp-1613058717.91-11463-153211684994567/AnsiballZ_command.py && sleep 0'
    amazon-ebs: <127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-ikhhmbyimkhnplenfeeltrtggdjcrqdk ; /usr/bin/python /home/admin/.ansible/tmp/ansible-tmp-1613058717.91-11463-153211684994567/AnsiballZ_command.py'"'"' && sleep 0'
    amazon-ebs: <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/admin/.ansible/tmp/ansible-tmp-1613058717.91-11463-153211684994567/ > /dev/null 2>&1 && sleep 0'
    amazon-ebs: The full traceback is:
    amazon-ebs: Traceback (most recent call last):
    amazon-ebs:   File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 158, in run
    amazon-ebs:     res = self._execute()
    amazon-ebs:   File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 663, in _execute
    amazon-ebs:     result = self._handler.run(task_vars=variables)
    amazon-ebs:   File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/shell.py", line 25, in run
    amazon-ebs:     result = command_action.run(task_vars=task_vars)
    amazon-ebs:   File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/command.py", line 30, in run
    amazon-ebs:     self._remove_tmp_path(self._connection._shell.tmpdir)
    amazon-ebs:   File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 452, in _remove_tmp_path
    amazon-ebs:     tmp_rm_res = self._low_level_execute_command(cmd, sudoable=False)
    amazon-ebs:   File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/action/__init__.py", line 1121, in _low_level_execute_command
    amazon-ebs:     rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
    amazon-ebs:   File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/local.py", line 89, in exec_command
    amazon-ebs:     stderr=subprocess.PIPE,
    amazon-ebs:   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    amazon-ebs:     errread, errwrite)
    amazon-ebs:   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    amazon-ebs:     raise child_exception
    amazon-ebs: OSError: [Errno 2] No such file or directory: '/tmp/packer-provisioner-ansible-local/60255176-b533-bffd-061d-ecf0a2843aa7'
    amazon-ebs: fatal: [127.0.0.1]: FAILED! => {
    amazon-ebs:     "msg": "Unexpected failure during module execution.",
    amazon-ebs:     "stdout": ""
    amazon-ebs: }
```

**Comment by nosrio** [comment]
I believe that removing the "rm -rf /tmp/*" will fix this issue. Is there any need to run that command at that task?

**Comment by miettal** [comment]
How about trying changing staging_directory? in packer config

it seems packer copy ansible provisioning script to staging_directory, it can be changed.
https://www.packer.io/docs/provisioners/ansible/ansible-local

**Comment by dj-wasabi** [comment]
The `rm -rf /tmp/*` has been removed (already). Will close this issue.
