### ISSUE TITLE
Playbook failing.. getting KeyError inventory_mode

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#35]
_From @dj-wasabi on 6 Mar 2020_

##### SUMMARY
I have created a simple playbook that points to the role dj-wasabi.zabbix-agent, which is installed by AWX on the flight.
The playbook has worked earlier (two days ago) and not it doesn't work anymore.

I receive following issue, when running the playbook on my ansible server (towards every host).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION
```paste below
ansible 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/tobias/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
bash-4.4# cat roles/requirements.yml
---
- src: https://github.com/dj-wasabi/ansible-zabbix-agent
  version: master
  name: dj-wasabi.zabbix-agent
```
Having the following ansible vars set:
```yaml
zabbix_agent_firewalld_enable: true
zabbix_agent_server: 10.0.1.XXX
zabbix_agent_serveractive: 10.0.1.XXX
zabbix_api_create_hosts: true
zabbix_api_create_hostgroup: true
zabbix_api_use: true
zabbix_api_user: YYY
zabbix_api_pass: ZZZ
zabbix_useuip: 1
zabbix_host_groups:
  - "Linux servers"
zabbix_link_templates:
  - "Template OS Linux by Zabbix agent"
zabbix_url: 'http://10.0.1.XXX'
zabbix_selinux: true
```
Following is part of the playbook.yml
```yaml
- hosts: all
  roles:
      - role: dj-wasabi.zabbix-agent
```

##### EXPECTED RESULTS

Succesful host creation in the Zabbix Web interface.

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1583395986.5052142-98721871607287/AnsiballZ_zabbix_host.py", line 114, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1583395986.5052142-98721871607287/AnsiballZ_zabbix_host.py", line 106, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1583395986.5052142-98721871607287/AnsiballZ_zabbix_host.py", line 49, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/usr/lib64/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 170, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/ansible_zabbix_host_payload_bm7p5trw/__main__.py", line 857, in <module>
  File "/tmp/ansible_zabbix_host_payload_bm7p5trw/__main__.py", line 817, in main
  File "/tmp/ansible_zabbix_host_payload_bm7p5trw/__main__.py", line 502, in check_all_properties
KeyError: 'inventory_mode'
fatal: [psg1-lobbymirror-001.home -> localhost]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1583395986.5052142-98721871607287/AnsiballZ_zabbix_host.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1583395986.5052142-98721871607287/AnsiballZ_zabbix_host.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1583395986.5052142-98721871607287/AnsiballZ_zabbix_host.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib64/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib64/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_zabbix_host_payload_bm7p5trw/__main__.py\", line 857, in <module>\n  File \"/tmp/ansible_zabbix_host_payload_bm7p5trw/__main__.py\", line 817, in main\n  File \"/tmp/ansible_zabbix_host_payload_bm7p5trw/__main__.py\", line 502, in check_all_properties\nKeyError: 'inventory_mode'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
Link: dj-wasabi/ansible-zabbix-agent#308

_Copied from original issue ansible/ansible#68088_

**Comment by D3DeFi** [comment]
Patch ansible/ansible#66860 for this issue haven't made it to the ansible before `devel` branch freeze so the bug persists and the PR needs to be reopened here.

**Comment by D3DeFi** [comment]
This was fixed somewhere at some point and as discussed [this comment](https://github.com/ansible-collections/community.zabbix/issues/34#issuecomment-645963990) it should no longer be a problem.
