### ISSUE TITLE
Zabbix Agent for Windows install config error(file not found)

### ISSUE THREAD

**Issue by valentusys** [ansible-collections/community.zabbix#577]
##### SUMMARY
When trying to create a zabbix-agent configuration, ansible says that the file does not exist. Although it is at this path that the file is present.
All previous tasks are performed correctly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

TASK [community.zabbix.zabbix_agent : Windows | Configure zabbix-agent]

##### ANSIBLE VERSION

```ansible [core 2.11.7] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True


```

##### CONFIGURATION

```DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent

```

##### OS / ENVIRONMENT / Zabbix Version

Windows 10 Pro x64

##### STEPS TO REPRODUCE

```test.yml:
---
- name: Using Zabbix collection
  hosts: all
  roles:
    - role: community.zabbix.zabbix_agent
      zabbix_win_install_dir: 'C:\zabbix'
      zabbix_agent_win_logfile: 'C:\zabbix\agent.log'
      zabbix_agent(2)_logfilesize: 1
      zabbix_version_long: 5.2.7
      zabbix_agent2: true
      zabbix_agent_version: 5.2
      zabbix_repo: other
      zabbix_agent_serveractive: zabbix
      zabbix_win_download_link: 'http://X.X.X.X/zbx-agent/zabbix_agent2-5.2.7-windows-amd64-openssl-static.zip'
      zabbix_agent_win_include: 'C:\zabbix\custom'
      
  vars:
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_transport: kerberos
    ansible_user: ***
    ansible_password: ***
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_connection_timeout: 30
    #stdout_callback: minimal


```

##### EXPECTED RESULTS

Correct generate zabbix_agent2.conf

##### ACTUAL RESULTS

Error "No such file or directory: b'C:\\zabbix\\\\conf\\\\zabbix_agent2.conf'"

```TASK [community.zabbix.zabbix_agent : Windows | Configure zabbix-agent] ************************************************************************************
task path: /root/.ansible/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/Windows_conf.yml:10
<COMPUTERNAME> ESTABLISH WINRM CONNECTION FOR USER: ansible@DOMAIN on PORT 5986 TO COMPUTERNAME
calling kinit with subprocess for principal ansible@DOMAIN
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/collections/ansible_collections/ansible/windows/plugins/action/win_template.py", line 126, in run
    temp_vars.update(generate_ansible_template_vars(source, dest))
  File "/usr/lib/python3/dist-packages/ansible/template/__init__.py", line 111, in generate_ansible_template_vars
    template_uid = pwd.getpwuid(os.stat(b_path).st_uid).pw_name
FileNotFoundError: [Errno 2] No such file or directory: b'C:\\zabbix\\\\conf\\\\zabbix_agent2.conf'
fatal: [COMPUTERNAME]: FAILED! => {
    "changed": false,
    "msg": "FileNotFoundError: [Errno 2] No such file or directory: b'C:\\\\zabbix\\\\\\\\conf\\\\\\\\zabbix_agent2.conf'"




```

![RemoteDesktopManager64_yTVt1B3PpU](https://user-images.githubusercontent.com/47516668/146724193-ba25e1e0-d1c9-4a09-90a4-56e12084c971.png)

**Comment by dj-wasabi** [comment]
I am not a Windows user (Unless I want some fresh air or want to know where I am driving to in my car) but this is probably related to the single vs double slashes?

**Comment by valentusys** [comment]
Maybe.
But even when I wrote the path manually in \root\.ansible\collections\ansible_collections\community\zabbix\roles\zabbix_agent\tasks\Windows_conf.yml
It doesn't work either.

And all the previous steps, with paths, work correctly.

**Comment by valentusys** [comment]
I'm sorry - the problem was with ansible.windows.

Updating to the current version solved the problem.

Thank you

**Comment by dj-wasabi** [comment]
> I'm sorry - the problem was with ansible.windows.
> 
> Updating to the current version solved the problem.
> 
> Thank you

No worries, glad it is solved now.
