### ISSUE TITLE
Zabbix 6.2. Can't create template using community.zabbix.zabbix_template

### ISSUE THREAD

**Issue by oupfiz5** [ansible-collections/community.zabbix#736]
##### SUMMARY
Can't create template using community.zabbix.zabbix_template

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.zabbix.zabbix_template

##### ANSIBLE VERSION
```
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/v/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/ansible
  ansible collection location = /home/v/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/v/.pyenv/versions/ansible-3.10.5/bin/ansible
  python version = 3.10.5 (main, Jul  7 2022, 19:50:26) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION
```

```

##### OS / ENVIRONMENT / Zabbix Version
Ubuntu 20.04.4 LTS
Zabbix 6.2
community.zabbix 1.7.0

##### STEPS TO REPRODUCE

```yaml
- name: Create a new Zabbix template Web Monitoring linked to groups, macros and templates
  local_action:
    module: community.zabbix.zabbix_template
    server_url: "http://127.0.0.1"
    login_user: Admin
    login_password: zabbix
    template_name: "Web Monitoring"
    template_groups:
     - 'Zabbix servers'
    macros:
      - macro: '{$EXAMPLE_MACRO1}'
        value: 30000
    state: present
```

##### EXPECTED RESULTS
Create new template

##### ACTUAL RESULTS
```
-> ansible-playbook  ./zabbix.yaml --connection=local -vvv
ansible-playbook [core 2.13.1]
  config file = None
  configured module search path = ['/home/v/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/ansible
  ansible collection location = /home/v/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/v/.pyenv/versions/ansible-3.10.5/bin/ansible-playbook
  python version = 3.10.5 (main, Jul  7 2022, 19:50:26) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: zabbix.yaml **********************************************************************************************************************
1 plays in ./zabbix.yaml

PLAY [Using Zabbix collection] *************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
task path: /home/v/tmp/zabbix/zabbix.yaml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: v
<127.0.0.1> EXEC /bin/sh -c 'echo ~v && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/v/.ansible/tmp `"&& mkdir "` echo /home/v/.ansible/tmp/ansible-tmp-1657551920.8191006-160597-92214397879011 `" && echo ansible-tmp-1657551920.8191006-160597-92214397879011="` echo /home/v/.ansible/tmp/ansible-tmp-1657551920.8191006-160597-92214397879011 `" ) && sleep 0'
Using module file /home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/v/.ansible/tmp/ansible-local-1604512jhyu1yt/tmpdab8hc51 TO /home/v/.ansible/tmp/ansible-tmp-1657551920.8191006-160597-92214397879011/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/v/.ansible/tmp/ansible-tmp-1657551920.8191006-160597-92214397879011/ /home/v/.ansible/tmp/ansible-tmp-1657551920.8191006-160597-92214397879011/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/v/.pyenv/versions/ansible-3.10.5/bin/python /home/v/.ansible/tmp/ansible-tmp-1657551920.8191006-160597-92214397879011/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/v/.ansible/tmp/ansible-tmp-1657551920.8191006-160597-92214397879011/ > /dev/null 2>&1 && sleep 0'
ok: [127.0.0.1]
META: ran handlers

TASK [include_role : zabbix_template] ******************************************************************************************************
task path: /home/v/tmp/zabbix/zabbix.yaml:11

TASK [zabbix_template : Create a new Zabbix template Web Monitoring linked to groups, macros and templates] ********************************
task path: /home/v/tmp/zabbix/roles/zabbix_template/tasks/main.yml:48
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: v
<localhost> EXEC /bin/sh -c 'echo ~v && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/v/.ansible/tmp `"&& mkdir "` echo /home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625 `" && echo ansible-tmp-1657551922.1685877-160697-194270399371625="` echo /home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625 `" ) && sleep 0'
Using module file /home/v/.ansible/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py
<localhost> PUT /home/v/.ansible/tmp/ansible-local-1604512jhyu1yt/tmpiff8jb0o TO /home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/ /home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py && sleep 0'
<localhost> EXEC /bin/sh -c '/home/v/.pyenv/versions/ansible-3.10.5/bin/python /home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py", line 107, in <module>
    _ansiballz_main()
  File "/home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_template', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_template', _modlib_path=modlib_path),
  File "/home/v/.pyenv/versions/3.10.5/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/v/.pyenv/versions/3.10.5/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/v/.pyenv/versions/3.10.5/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_template_payload_4degprx9/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py", line 795, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_template_payload_4degprx9/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py", line 774, in main
  File "/tmp/ansible_community.zabbix.zabbix_template_payload_4degprx9/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py", line 372, in add_template
  File "/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py", line 341, in method
    return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
  File "/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py", line 79, in wrapper
    return self.do_request(self.json_obj(method, opts))['result']
  File "/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py", line 348, in do_request
    return self.parent.do_request(req)
  File "/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py", line 299, in do_request
    raise ZabbixAPIException(msg, jobj['error']['code'])
zabbix_api.ZabbixAPIException: ('Error -32500: Application error., No permissions to referred object or it does not exist! while sending {"jsonrpc": "2.0", "method": "template.create", "params": {"host": "Web Monitoring", "groups": [{"groupid": "4"}], "templates": [], "macros": [{"macro": "{$EXAMPLE_MACRO1}", "value": "30000"}]}, "auth": "198d01655597e58ef3b810e70f7cf2a4", "id": 5}', -32500)
fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/v/.ansible/tmp/ansible-tmp-1657551922.1685877-160697-194270399371625/AnsiballZ_zabbix_template.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_template', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_template', _modlib_path=modlib_path),\n  File \"/home/v/.pyenv/versions/3.10.5/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/home/v/.pyenv/versions/3.10.5/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/home/v/.pyenv/versions/3.10.5/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_template_payload_4degprx9/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 795, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_template_payload_4degprx9/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 774, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_template_payload_4degprx9/ansible_community.zabbix.zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 372, in add_template\n  File \"/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py\", line 341, in method\n    return self.universal(\"%s.%s\" % (self.data[\"prefix\"], name), opts[0])\n  File \"/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py\", line 79, in wrapper\n    return self.do_request(self.json_obj(method, opts))['result']\n  File \"/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py\", line 348, in do_request\n    return self.parent.do_request(req)\n  File \"/home/v/.pyenv/versions/ansible-3.10.5/lib/python3.10/site-packages/zabbix_api.py\", line 299, in do_request\n    raise ZabbixAPIException(msg, jobj['error']['code'])\nzabbix_api.ZabbixAPIException: ('Error -32500: Application error., No permissions to referred object or it does not exist! while sending {\"jsonrpc\": \"2.0\", \"method\": \"template.create\", \"params\": {\"host\": \"Web Monitoring\", \"groups\": [{\"groupid\": \"4\"}], \"templates\": [], \"macros\": [{\"macro\": \"{$EXAMPLE_MACRO1}\", \"value\": \"30000\"}]}, \"auth\": \"198d01655597e58ef3b810e70f7cf2a4\", \"id\": 5}', -32500)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

PS The same playbook is working under Zabbix 6.0.6
```yaml
-> ansible-playbook  ./zabbix.yaml --connection=local

PLAY [Using Zabbix collection] *************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [127.0.0.1]

TASK [include_role : zabbix_template] ******************************************************************************************************

TASK [zabbix_template : Create a new Zabbix template Web Monitoring linked to groups, macros and templates] ********************************
changed: [127.0.0.1 -> localhost]

PLAY RECAP *********************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by oupfiz5** [comment]
[From API ](https://www.zabbix.com/documentation/current/en/manual/api/reference/template/create) is waiting [Template groups](https://www.zabbix.com/documentation/current/en/manual/api/reference/templategroup/object) . [From ansible ](https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_template_module.html#ansible-collections-community-zabbix-zabbix-template-module) is waiting` List of host groups to add template` .  May be it is problem ?

**Comment by BGmot** [comment]
I think yes: https://www.zabbix.com/documentation/current/en/manual/api/changes_6.0_-_6.2#template-1
