### ISSUE TITLE
community.zabbix.zabbix_host: UnboundLocalError: local variable 'found' referenced before assignment

### ISSUE THREAD

**Issue by dgibbs64** [ansible-collections/community.zabbix#791]
##### SUMMARY

When running the below task and the host already exists it returns a python error `UnboundLocalError: local variable 'found' referenced before assignment`. On first run is is fine.
##### ISSUE TYPE
- Bug Report

```- name: ensure host is added to Zabbix Server
  local_action:
    module: community.zabbix.zabbix_host
    server_url: https://example.com
    login_user: admin
    login_password: "password"
    host_name: "host.server.com"
    visible_name: "Server"
    validate_certs: false
    host_groups:
      - group
      - group2
    link_templates:
      - template
    state: present
```

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'found' referenced before assignment
fatal: [host.server.com -> localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "", line 107, in 
  File "", line 99, in _ansiballz_main
  File "", line 47, in invoke_module
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_g0isnu3j/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1271, in 
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_g0isnu3j/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1217, in main
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_g0isnu3j/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 732, in check_all_properties
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_g0isnu3j/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 706, in check_interface_properties
UnboundLocalError: local variable 'found' referenced before assignment
```
##### ANSIBLE VERSION

```paste below
ansible [core 2.13.3]
  config file = None
  configured module search path = ['/home/www/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/www/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = Trues
```

##### CONFIGURATION

```paste below
blank
```

##### OS / ENVIRONMENT / Zabbix Version

debian based docker container (local_action)

##### STEPS TO REPRODUCE

run the task once and it passes run again and it errors

```yaml

```

##### EXPECTED RESULTS

task runs repeatedly

##### ACTUAL RESULTS

task fails on second run

```paste below

```

**Comment by mu1f407** [comment]
Thank you for the report @dgibbs64. It should be fixed in linked PR. I think it's not very common to create a host without interfaces. We haven't got the update of host without interface covered in tests.

**Comment by dgibbs64** [comment]
Thank you for the fast response 😊. In my use case the host is used to monitor a domain only using the http agent. I did this to make it easy to monitor multiple vhosts on the same server.
