### ISSUE TITLE
Can't change zabbix_url_path

### ISSUE THREAD

**Issue by Zuko** [ansible-collections/community.zabbix#894]
##### SUMMARY
Maybe I'm missed something obvious here, but I can't set `ansible_zabbix_url_path` variable…

My Zabbix Server is running in "root" context `https://<FQDN>/`, but role always try to connect `https://<FQDN>/zabbix`, I tried overwriting `ansible_zabbix_url_path` variable in "multiple" places, but as Ansible docs state that `extra vars (for example, -e "user=my_user")(always win precedence)` "always win" and after adding variable there it still doesn't work - something must be wrong.

Workaround:
Comment [../httpapi/zabbix.py#L117](https://github.com/ansible-collections/community.zabbix/blob/main/plugins/httpapi/zabbix.py#L117) line…

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Zabbix_Agent Role version 1.9.1 / HTTPAPI Plugin

##### ANSIBLE VERSION
```
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/zuko/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/zuko/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/zuko/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/zuko/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION
```
CONFIG_FILE() = /home/zuko/repo/ansible/ansible.cfg
DEFAULT_FORKS(/home/zuko/repo/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/zuko/repo/ansible/ansible.cfg) = ['/home/zuko/repo/ansible-vm-inventory/hosts']
DEFAULT_VAULT_PASSWORD_FILE(/home/zuko/repo/ansible/ansible.cfg) = <REDACTED>
```

##### OS / ENVIRONMENT / Zabbix Version
Target: Debian 11
Zabbix Server: 6.0.13

##### STEPS TO REPRODUCE
Playbook:
```yaml
---
# code: language=ansible
- name: Install Zabbix Agent
  hosts: "{{ target_host | default([]) }}"

  handlers:
    - name: Import Handlers
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Configure Zabbix-Agent
      ansible.builtin.include_role:
        name: community.zabbix.zabbix_agent # External
      when:
        - defaults_configure_zabbix
      tags:
        - zabbix

    - name: Import Zabbix Config Tasks
      ansible.builtin.import_tasks:
        file: tasks/zabbix-defaults.yml
      when:
        - defaults_configure_zabbix
      tags:
        - zabbix
```

Command:
```bash
ansible-playbook zabbix-agent-install-simple.yml -e target_host=example.com -e ansible_zabbix_url_path='something_to_test'
```

##### EXPECTED RESULTS
Changed URL to `https://<FQDN>/something_to_test`

##### ACTUAL RESULTS
"Default" URL `https://<FQDN>/zabbix`

```
FAILED - RETRYING: [example.com -> zabbix.example.com]: API | Create a new host using agent2 or update an existing host's info (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/zuko/.ansible/tmp/ansible-local-22941e144jbpm/ansible-tmp-1675768997.989511-23375-235761357518746/AnsiballZ_zabbix_host.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/zuko/.ansible/tmp/ansible-local-22941e144jbpm/ansible-tmp-1675768997.989511-23375-235761357518746/AnsiballZ_zabbix_host.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/zuko/.ansible/tmp/ansible-local-22941e144jbpm/ansible-tmp-1675768997.989511-23375-235761357518746/AnsiballZ_zabbix_host.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_twolpr86/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1289, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_twolpr86/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1083, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_twolpr86/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 33, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_twolpr86/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_twolpr86/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.\n\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "retries": 4
}
```
nginx access log:
```
<REDACTED> - <ZABBIX_USER> [07/Feb/2023:14:04:06 +0100] "POST /zabbix/api_jsonrpc.php HTTP/1.1" 404 27 "-" "Python-urllib/3.10"
```

nginx error log:
```
2023/02/07 12:23:39 [error] 3201699#3201699: *230155 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: <REDACTED>, server: example.com, request: "POST /zabbix/api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "example.com:443"
```

**Comment by BGmot** [comment]
Try
```
- name: Install Zabbix Agent
  hosts: "{{ target_host | default([]) }}"
  vars:
    ansible_zabbix_url_path: "/"
```

**Comment by Zuko** [comment]
Same result.

I also tried:
- inventory
- set_fact
- group_vars/all.yaml

**Comment by BGmot** [comment]
Since you are comfortable updating the collection code try adding one line after this one https://github.com/ansible-collections/community.zabbix/blob/main/plugins/httpapi/zabbix.py#L99
```
raise Exception(url_path)
```
and see what you get in the exception message.

**Comment by Zuko** [comment]
Playbook fragment:
```yaml
---
# code: language=ansible
- name: Install Zabbix Agent
  hosts: "{{ target_host | default([]) }}"
  vars:
    ansible_zabbix_url_path: "/"
…
```

../httpapi/zabbix.py:
```yaml
…
    def api_version(self):
        url_path = self.get_option('zabbix_url_path')
        raise Exception(url_path)
        if isinstance(url_path, str):
            # zabbix_url_path provided (even if it is an empty string)
…
```

Log:
```yaml
The full traceback is:
Traceback (most recent call last):
  File "/home/zuko/.ansible/tmp/ansible-local-527264q6q_ljq/ansible-tmp-1675789717.5202122-53127-184988277198239/AnsiballZ_zabbix_host.py", line 107, in <module>
    _ansiballz_main()
  File "/home/zuko/.ansible/tmp/ansible-local-527264q6q_ljq/ansible-tmp-1675789717.5202122-53127-184988277198239/AnsiballZ_zabbix_host.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/zuko/.ansible/tmp/ansible-local-527264q6q_ljq/ansible-tmp-1675789717.5202122-53127-184988277198239/AnsiballZ_zabbix_host.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1289, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1083, in main
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 33, in __init__
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: zabbix
fatal: [admin.nf -> zabbix.admin.ad.colorland.pl]: FAILED! => {
    "attempts": 3,
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/zuko/.ansible/tmp/ansible-local-527264q6q_ljq/ansible-tmp-1675789717.5202122-53127-184988277198239/AnsiballZ_zabbix_host.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/zuko/.ansible/tmp/ansible-local-527264q6q_ljq/ansible-tmp-1675789717.5202122-53127-184988277198239/AnsiballZ_zabbix_host.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/zuko/.ansible/tmp/ansible-local-527264q6q_ljq/ansible-tmp-1675789717.5202122-53127-184988277198239/AnsiballZ_zabbix_host.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.10/runpy.py\", line 224, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1289, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1083, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 33, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_bunnluz4/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: zabbix\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by BGmot** [comment]
I see that setting this variable has not effect in your case.
No idea why. I can test more later with your playbook but some time ago I was testing this variable with:
```
 hosts: all
  tasks:
  - name: Deploy 1.9 style
    include_role:
      name: community.zabbix.zabbix_agent
    vars:
      zabbix_api_create_hosts: True
      ansible_zabbix_url_path: ""
      <all_other_vars>
```
and it was working well.

**Comment by Zuko** [comment]
Ok, thanks. Waiting for your test results.

**Comment by BGmot** [comment]
This is my minimalistic playbook:
```
$ cat install_agent_path.yml
- name: Install Zabbix Agent
  hosts:
  - 192.168.155.201
  vars:
    zabbix_agent_ip: 192.168.155.201
    zabbix_api_create_hosts: True
    zabbix_api_create_hostgroup: False
    zabbix_api_server_host: 192.168.155.200
    zabbix_api_server_port: 8080
    zabbix_api_use_ssl: False
    zabbix_api_login_user: Admin
    zabbix_api_login_pass: zabbix
    ansible_zabbix_url_path: ''
    zabbix_agent_link_templates:
    - Linux by Zabbix agent

  tasks:
    - name: Configure Zabbix-Agent
      ansible.builtin.include_role:
        name: community.zabbix.zabbix_agent # External
```
I run it without problems and it provisions the host:
```
$ ansible-playbook -i 192.168.155.201, install_agent_path.yml -K
```

**Comment by Zuko** [comment]
Same result ;(

```yaml
- name: Install Zabbix Agent
  hosts:
    - 192.168.20.204
  vars:
    ansible_user: <ssh_user>
    ansible_port: <ssh_port>
    zabbix_agent_ip: 192.168.20.204
    zabbix_api_create_hosts: True
    zabbix_api_create_hostgroup: False
    zabbix_api_server_host: zabbix.<fqdn>
    zabbix_api_server_port: 443
    zabbix_api_use_ssl: True
    zabbix_api_login_user: ansible_test_user
    zabbix_api_login_pass: ansible_test_user
    ansible_zabbix_url_path: ''
    zabbix_agent_link_templates:
      - Linux by Zabbix agent

  tasks:
    - name: Configure Zabbix-Agent
      ansible.builtin.include_role:
        name: community.zabbix.zabbix_agent # External
```

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.
```

**Comment by Zuko** [comment]
Problem solved.

Dunno what exacly was wrong, but I just removed all collections from `$HOME/.ansible/collections` and reinstalled them.
