### ISSUE TITLE
netcommon 5.0.0 breaks Zabbix connection ('Connection' object has no attribute 'zbx_api_version')

### ISSUE THREAD

**Issue by weakcamel** [ansible-collections/community.zabbix#909]
##### SUMMARY

Without any obvious changes, my API calls to Zabbix started failing. Upon investigation, I discovered this is caused by latest ansible.netcommon module 5.0.0; downgrading to 4.1.0 fixes the problem.

Note that 5.0.0 was released yesterrday (1 March 2023):

https://github.com/ansible-collections/ansible.netcommon/blob/main/CHANGELOG.rst#v5-0-0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

httpapi plugin (I'm guessing)

##### ANSIBLE VERSION

```
root@966cd8bb9796:/code# ansible --version
ansible [core 2.13.7]
  config file = /code/ansible.cfg
  configured module search path = ['/code/library']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /code/galaxy-collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  jinja version = 3.1.2
  libyaml = True
```

##### CONFIGURATION

```
root@966cd8bb9796:/code# ansible-config dump --only-changed
ANSIBLE_COW_SELECTION(/code/ansible.cfg) = stegosaurus
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
ANSIBLE_NOCOWS(/code/ansible.cfg) = True
COLLECTIONS_PATHS(/code/ansible.cfg) = ['/code/galaxy-collections']
DEFAULT_FORKS(/code/ansible.cfg) = 20
DEFAULT_GATHER_TIMEOUT(/code/ansible.cfg) = 30
DEFAULT_HOST_LIST(/code/ansible.cfg) = ['/code/inventory/all.yml', '/code/inventory/dev_vms_inventory.sh']
DEFAULT_LOAD_CALLBACK_PLUGINS(/code/ansible.cfg) = False
DEFAULT_LOG_PATH(/code/ansible.cfg) = /code/log_ansible.txt
DEFAULT_MANAGED_STR(/code/ansible.cfg) = This file is being managed with Ansible. Do NOT update it manually.
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/code/library']
DEFAULT_ROLES_PATH(/code/ansible.cfg) = ['/code/galaxy-roles', '/code/roles']
DEFAULT_STDOUT_CALLBACK(/code/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/code/ansible.cfg) = 30
DEFAULT_TRANSPORT(/code/ansible.cfg) = ssh
HOST_KEY_CHECKING(/code/ansible.cfg) = False
INTERPRETER_PYTHON(/code/ansible.cfg) = /usr/bin/python3
INVENTORY_ANY_UNPARSED_IS_FAILED(/code/ansible.cfg) = True
INVENTORY_ENABLED(/code/ansible.cfg) = ['script', 'yaml', 'auto', 'host_list']
```

##### OS / ENVIRONMENT / Zabbix Version

Ubuntu 22.04 as controller host (running in a Docker container)

Target is Zabbix 6.2.7 on Ubuntu Jammy (22.04)

##### STEPS TO REPRODUCE

```yaml
...
- name: (Re)configure zabbix-agent for the server
  vars:
    gather_facts: false
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_user: "{{ zabbix_api_user }}"
    ansible_httpapi_pass: "{{ zabbix_api_pass }}"
  delegate_to: "{{ zabbix_api_server_host }}"
  become: false
  no_log: true
  community.zabbix.zabbix_host:  # noqa args[module]
    host_name: Zabbix server
    host_groups:
      - Linux servers
      - Zabbix servers
    link_templates:
      - Linux by Zabbix agent
      - Zabbix server health
    interfaces:
      - type: 1
        main: 1
        useip: 0
        dns: zabbix-agent
        port: "10050"
```

##### EXPECTED RESULTS
OK

##### ACTUAL RESULTS

```
TASK [community.zabbix.zabbix_agent : API | Create host groups] ****************
FAILED - RETRYING: [autobot.dev-vms.example.com -> zabbix.core.example.com]: API | Create host groups (3 retries left).
FAILED - RETRYING: [autobot.dev-vms.example.com -> zabbix.core.example.com]: API | Create host groups (2 retries left).
FAILED - RETRYING: [autobot.dev-vms.example.com -> zabbix.core.example.com]: API | Create host groups (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'
fatal: [autobot.dev-vms.example.com -> zabbix.core.example.com]: FAILED! => changed=false 
  attempts: 3
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 107, in <module>
      File "<stdin>", line 99, in _ansiballz_main
      File "<stdin>", line 47, in invoke_module
      File "/usr/lib/python3.10/runpy.py", line 224, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_wrrb24pp/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 193, in <module>
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_wrrb24pp/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 165, in main
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_wrrb24pp/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 33, in __init__
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_wrrb24pp/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_wrrb24pp/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

**Comment by weakcamel** [comment]
This is a re-occurence of https://github.com/ansible-collections/community.zabbix/issues/878 (sort of).

**Comment by xchotard-talentsoft** [comment]
Same issue here. Thanks to the author, I was able to downgrade netcommon as a workaround:
```
ansible-galaxy collection install ansible.netcommon:==4.1.0
```

**Comment by BGmot** [comment]
The issue confirmed. All our tests fail as well. Quick look did not give me any idea what broke this, will try to take a close look on the weekend.

**Comment by BGmot** [comment]
This line 269 removal https://github.com/ansible-collections/ansible.netcommon/pull/494/files#diff-a766d1a651d157b588c31d264a965764505f451a9ec15aad27aac98a4763b30aL269 leads to ignoring headers we ask netcommon to send to Zabbix Server and instead of `Content-Type: application/json-rpc` it sends `Content-Type: application/x-www-form-urlencoded` so Zabbix server of course chokes on this.
Please test the code from #915  - I tried to test with ansible.netcommon 4.1.0 and 5.0.0, both worked.

**Comment by epollia** [comment]
with 5.0.0 not working

**Comment by BGmot** [comment]
All our tests are working properly with 5.0.0 https://github.com/ansible-collections/community.zabbix/actions/runs/4400834355/jobs/7706495745#step:6:17
Before this merge they were failing with exactly the same error https://github.com/BGmot/community.zabbix/actions/runs/4339656928/jobs/7590173679#step:8:1009

So if it is still failing for you please provide exact code you are trying to execute so I can reproduce the failure.

**Comment by epollia** [comment]
```
TASK [community.zabbix.zabbix_agent : API | Create host groups]

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/epollia/.ansible/tmp/ansible-local-3363681a94gkiso/ansible-tmp-1678713313.2759242-3364451-78025693714172/AnsiballZ_zabbix_group.py", line 107, in <module>
    _ansiballz_main()
  File "/home/epollia/.ansible/tmp/ansible-local-3363681a94gkiso/ansible-tmp-1678713313.2759242-3364451-78025693714172/AnsiballZ_zabbix_group.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/epollia/.ansible/tmp/ansible-local-3363681a94gkiso/ansible-tmp-1678713313.2759242-3364451-78025693714172/AnsiballZ_zabbix_group.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_group', _modlib_path=modlib_path),
  File "/usr/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_1uynk2ky/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 193, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_1uynk2ky/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 165, in main
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_1uynk2ky/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 33, in __init__
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_1uynk2ky/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_1uynk2ky/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: 'Connection' object has no attribute 'zbx_api_version'```

Zabbix server version 4.4

**Comment by epollia** [comment]
I have set the collection as
`ansible-galaxy collection install ansible.netcommon:==5.0.0`
and got an error
With 4.1.0 all fine

**Comment by epollia** [comment]
```
Collection           Version
-------------------- -------
ansible.netcommon    5.0.0  
ansible.posix        1.5.1  
ansible.utils        2.9.0  
ansible.windows      1.13.0 
community.crypto     2.8.1  
community.docker     3.4.0  
community.general    6.4.0  
community.mysql      3.6.0  
community.postgresql 2.3.2  
community.zabbix     1.9.2  
```

**Comment by epollia** [comment]
![image](https://user-images.githubusercontent.com/35440159/224719965-131b0f3a-534e-42f5-8a03-c246ab2209f1.png)
with 5.0.0

**Comment by weakcamel** [comment]
> community.zabbix     1.9.2

Have you reinstalled the community.zabbix collection to pick up the fix though? Or is it vanilla 1.9.2 version?

**Comment by epollia** [comment]
it is vanilla version from ansible-galaxy

**Comment by weakcamel** [comment]
@epollia See https://github.com/ansible-collections/community.zabbix/issues/909#issuecomment-1464986141

> Please test the code from #915 - I tried to test with ansible.netcommon 4.1.0 and 5.0.0, both worked.

The issue was fixed already but there wasn't yet a public release by the authors; see that the latest release was a month ago: https://github.com/ansible-collections/community.zabbix/releases
