### ISSUE TITLE
Question: How to adapt to httpapi in the task?

### ISSUE THREAD

**Issue by duchenpaul** [ansible-collections/community.zabbix#946]
##### SUMMARY
I would like to connect to my zabbix via httpapi, suggested by the warning

##### ISSUE TYPE
- Question

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /app/ansible_code/ansible.cfg
  configured module search path = ['/home/pi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/pi/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Mar 23 2023, 17:12:29) [GCC 10.2.1 20210110] (/usr/local/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 6.2.3

##### STEPS TO REPRODUCE
My zabbix server and ansible controller runs on different servers, and this task is running against a zabbix agent host, it is used to register the host to the zabbix service.

My current working task:
```yaml
- name: Register {{ zabbix_host_hostname }} to zabbix server
  delegate_to: 127.0.0.1
  community.zabbix.zabbix_host:
    server_url: "{{ zabbix_server_url }}"
    login_user: "{{ zabbix_username }}"
    login_password: "{{ zabbix_password }}"
    description: "Host server: {{ inventory_hostname }}"
    force: yes
    host_name: "{{ zabbix_host_hostname }}"
    visible_name: "{{ zabbix_host_alias | default(zabbix_host_hostname) }}"
    # inventory_mode: automatic
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        port: "10050"
    link_templates: "{{ zabbix_link_templates }}"
    host_groups: "{{ host_groups }}"
    timeout: 40
    proxy: "{{ zabbix_proxy | default() }}"
  retries: 10
  delay: 3
```

Tried to convert to httpapi connection:
```yaml
- name: Register {{ zabbix_host_hostname }} to zabbix server
  delegate_to: 127.0.0.1
  community.zabbix.zabbix_host:
    description: "Host server: {{ inventory_hostname }}"
    force: yes
    host_name: "{{ zabbix_host_hostname }}"
    visible_name: "{{ zabbix_host_alias | default(zabbix_host_hostname) }}"
    # inventory_mode: automatic
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        port: "10050"
    link_templates: "{{ zabbix_link_templates }}"
    host_groups: "{{ host_groups }}"
    timeout: 40
    proxy: "{{ zabbix_proxy | default() }}"
  retries: 10
  delay: 3
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_host: "{{ zabbix_server }}"
    ansible_httpapi_port: "{{ zabbix_http_port }}"
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
    ansible_user: "{{ zabbix_username }}"
    ansible_httpapi_pass: "{{ zabbix_password }}"
```

Using environment vars:
```yaml
- name: Register {{ zabbix_host_hostname }} to zabbix server
  delegate_to: "{{ zabbix_server }}"
  community.zabbix.zabbix_host:
    description: "Host server: {{ inventory_hostname }}"
    force: yes
    host_name: "{{ zabbix_host_hostname }}"
    visible_name: "{{ zabbix_host_alias | default(zabbix_host_hostname) }}"
    # inventory_mode: automatic
    interfaces:
      - type: agent
        main: 1
        useip: 1
        ip: "{{ ansible_host }}"
        port: "10050"
    link_templates: "{{ zabbix_link_templates }}"
    host_groups: "{{ host_groups }}"
    timeout: 40
    proxy: "{{ zabbix_proxy | default() }}"
  retries: 10
  delay: 3
  vars:
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    ansible_httpapi_port: "{{ zabbix_http_port }}"
    ansible_httpapi_use_ssl: false
    ansible_httpapi_validate_certs: false
  environment:
    ZABBIX_SERVER: "{{ zabbix_server }}"
    ZABBIX_USERNAME: "{{ zabbix_username }}"
    ZABBIX_PASSWORD: "{{ zabbix_password }}"
```

Neither of the above working with httpapi connection, not sure why

##### EXPECTED RESULTS
To be the same result as my current working task

##### ACTUAL RESULTS
I got below errors (both):
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.
fatal: [venus -> 192.168.31.214]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/tmp/ansible-tmp-1681047795.8703089-709-254307844167501/AnsiballZ_zabbix_host.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/var/tmp/ansible-tmp-1681047795.8703089-709-254307844167501/AnsiballZ_zabbix_host.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/tmp/ansible-tmp-1681047795.8703089-709-254307844167501/AnsiballZ_zabbix_host.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1302, in <module>\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py\", line 1096, in main\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py\", line 33, in __init__\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py\", line 53, in api_version\n  File \"/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.\n\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

Decoded error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.
fatal: [venus -> 192.168.31.214]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):
  File "/var/tmp/ansible-tmp-1681047795.8703089-709-254307844167501/AnsiballZ_zabbix_host.py", line 107, in <module>
    _ansiballz_main()
  File "/var/tmp/ansible-tmp-1681047795.8703089-709-254307844167501/AnsiballZ_zabbix_host.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/tmp/ansible-tmp-1681047795.8703089-709-254307844167501/AnsiballZ_zabbix_host.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_host', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_host', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1302, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_host.py", line 1096, in main
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 33, in __init__
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
  File "/tmp/ansible_community.zabbix.zabbix_host_payload_7jwu1ys9/ansible_community.zabbix.zabbix_host_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: Invalid JSON response: File not found.

```

**Comment by BGmot** [comment]
Hi,
no need to use environment variables. Looks like your Zabbix is running not from /zabbx path. Try adding `ansible_zabbix_url_path` variable specifying the path or just `/` if it is running at root.
https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_host.py#L377

**Comment by duchenpaul** [comment]
my zabbix is running from /zabbix path, this is my zabbix url: `http://monitor.homes/zabbix.php?action=dashboard.view`, it is not open to public though.

**Comment by BGmot** [comment]
No, your path is '/'.

**Comment by BGmot** [comment]
If you had /zabbix then URL would be http://monitor.homes/zabbix/zabbix.php?action=dashboard.view

**Comment by duchenpaul** [comment]
No, my zabbix url is just http://monitor.homes/zabbix.php?action=dashboard.view

**Comment by BGmot** [comment]
I told you what to do, just try and close this issue if resolved.

**Comment by duchenpaul** [comment]
I resolved it by explicitly specifying `ansible_zabbix_url_path: ""`

Reference: https://tekunabe.hatenablog.jp/entry/2022/12/22/083529
