### ISSUE TITLE
Collection 2.0.0 - HTTP Basic Authentication not working

### ISSUE THREAD

**Issue by Thulium-Drake** [ansible-collections/community.zabbix#989]
##### SUMMARY

HTTP Basic authentication is not working, #565 is back for a second round..

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zabbix_agent
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT / Zabbix Version

Zabbix 6.0
Debian 11

##### STEPS TO REPRODUCE

Run a play with the Agent role and the config below against a Zabbix server with SSL and HTTP Basic auth enabled.

```yaml
---
###
# Zabbix agent configuration
###
zabbix_version: '6.0'
zabbix_agent_version: "{{ zabbix_version }}"
zabbix_server_version: "{{ zabbix_version }}"
zabbix_repo: 'zabbix'

zabbix_agent_server: 'monitoring.zm1.element-networks.nl,10.1.1.36'
zabbix_agent_serveractive: "{{ zabbix_agent_server }}"

zabbix_api_server_host: 'monitoring.zm1.element-networks.nl'
zabbix_api_server_port: 443
zabbix_api_use_ssl: true
zabbix_api_login_user: 'zabbix-cli'
zabbix_api_validate_certs: true
zabbix_api_login_pass: 'ssshhh!'

zabbix_api_create_hosts: true
zabbix_api_create_hostgroup: true
zabbix_agent_tlspsk_auto: true

```

##### ACTUAL RESULTS

```paste below
TASK [community.zabbix.zabbix_agent : API | Create host groups] ******************************************************************************************************************************************************************************
task path: /root/projects/element-networks/collections/ansible_collections/community/zabbix/roles/zabbix_agent/tasks/api.yml:2
Callback Exception: 
  File "/usr/lib/python3/dist-packages/ansible/executor/task_queue_manager.py", line 450, in send_callback
    method(*new_args, **kwargs)
   File "/root/projects/element-networks/library/callback/ara_default.py", line 373, in v2_playbook_on_task_start
    task_file = self._get_or_create_file(path)
   File "/root/projects/element-networks/library/callback/ara_default.py", line 489, in _get_or_create_file
    "/api/v1/files", playbook=self.playbook["id"], path=path, content=content
redirecting (type: connection) ansible.builtin.httpapi to ansible.netcommon.httpapi
<monitoring.zm1.element-networks.nl> ESTABLISH LOCAL CONNECTION FOR USER: root
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9 `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445 `" && echo ansible-tmp-1684227521.4699144-590767-258033702261445="` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445 `" ) && sleep 0'
Using module file /root/projects/element-networks/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py
<monitoring.zm1.element-networks.nl> PUT /root/.ansible/tmp/ansible-local-5904672d7xp3y9/tmpbm88nbtu TO /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/AnsiballZ_zabbix_group.py
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/ /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: [config.zm1.element-networks.nl -> monitoring.zm1.element-networks.nl]: API | Create host groups (3 retries left).Result was: changed=false 
  attempts: 1
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/AnsiballZ_zabbix_group.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/AnsiballZ_zabbix_group.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227521.4699144-590767-258033702261445/AnsiballZ_zabbix_group.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_group', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_igw5467p/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 181, in <module>
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_igw5467p/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 153, in main
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_igw5467p/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_igw5467p/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_igw5467p/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: HTTP Error 401: Unauthorized
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
  retries: 4
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9 `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331 `" && echo ansible-tmp-1684227527.0935867-590767-70430168219331="` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331 `" ) && sleep 0'
Using module file /root/projects/element-networks/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py
<monitoring.zm1.element-networks.nl> PUT /root/.ansible/tmp/ansible-local-5904672d7xp3y9/tmpvs7kqbt4 TO /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/AnsiballZ_zabbix_group.py
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/ /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: [config.zm1.element-networks.nl -> monitoring.zm1.element-networks.nl]: API | Create host groups (2 retries left).Result was: changed=false 
  attempts: 2
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/AnsiballZ_zabbix_group.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/AnsiballZ_zabbix_group.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227527.0935867-590767-70430168219331/AnsiballZ_zabbix_group.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_group', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_ti9huvs9/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 181, in <module>
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_ti9huvs9/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 153, in main
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_ti9huvs9/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_ti9huvs9/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_ti9huvs9/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: HTTP Error 401: Unauthorized
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
  retries: 4
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9 `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973 `" && echo ansible-tmp-1684227532.9094396-590767-65942560954973="` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973 `" ) && sleep 0'
Using module file /root/projects/element-networks/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py
<monitoring.zm1.element-networks.nl> PUT /root/.ansible/tmp/ansible-local-5904672d7xp3y9/tmpldt5me1w TO /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/AnsiballZ_zabbix_group.py
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/ /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: [config.zm1.element-networks.nl -> monitoring.zm1.element-networks.nl]: API | Create host groups (1 retries left).Result was: changed=false 
  attempts: 3
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/AnsiballZ_zabbix_group.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/AnsiballZ_zabbix_group.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227532.9094396-590767-65942560954973/AnsiballZ_zabbix_group.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_group', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_bcogy3un/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 181, in <module>
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_bcogy3un/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 153, in main
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_bcogy3un/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_bcogy3un/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_bcogy3un/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: HTTP Error 401: Unauthorized
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
  retries: 4
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9 `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663 `" && echo ansible-tmp-1684227538.328675-590767-11316766165663="` echo /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663 `" ) && sleep 0'
Using module file /root/projects/element-networks/collections/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py
<monitoring.zm1.element-networks.nl> PUT /root/.ansible/tmp/ansible-local-5904672d7xp3y9/tmpjphqlwvl TO /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/ /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py && sleep 0'
<monitoring.zm1.element-networks.nl> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_group', _modlib_path=modlib_path),
  File "/usr/lib/python3.9/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 181, in <module>
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 153, in main
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
  File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
ansible.module_utils.connection.ConnectionError: HTTP Error 401: Unauthorized
fatal: [config.zm1.element-networks.nl -> monitoring.zm1.element-networks.nl]: FAILED! => changed=false 
  attempts: 3
  module_stderr: |-
    Traceback (most recent call last):
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py", line 107, in <module>
        _ansiballz_main()
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/root/.ansible/tmp/ansible-local-5904672d7xp3y9/ansible-tmp-1684227538.328675-590767-11316766165663/AnsiballZ_zabbix_group.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_group', init_globals=dict(_module_fqn='ansible_collections.community.zabbix.plugins.modules.zabbix_group', _modlib_path=modlib_path),
      File "/usr/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
      File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
      File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 181, in <module>
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_group.py", line 153, in main
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/base.py", line 20, in __init__
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible_collections/community/zabbix/plugins/module_utils/api_request.py", line 53, in api_version
      File "/tmp/ansible_community.zabbix.zabbix_group_payload_y582beot/ansible_community.zabbix.zabbix_group_payload.zip/ansible/module_utils/connection.py", line 200, in __rpc__
    ansible.module_utils.connection.ConnectionError: HTTP Error 401: Unauthorized
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible.plugins.callback.ara_default.CallbackModule object at 0x7f05067e7220>): 'NoneType' object is not subscriptable
Callback Exception: 
  File "/usr/lib/python3/dist-packages/ansible/executor/task_queue_manager.py", line 450, in send_callback
    method(*new_args, **kwargs)
   File "/root/projects/element-networks/library/callback/ara_default.py", line 391, in v2_runner_on_failed
    self._submit_thread("task", self._load_result, result, "failed", **kwargs)
   File "/root/projects/element-networks/library/callback/ara_default.py", line 249, in _submit_thread
    func(*args, **kwargs)
   File "/root/projects/element-networks/library/callback/ara_default.py", line 546, in _load_result
    host = self._get_or_create_host(hostname)
   File "/root/projects/element-networks/library/callback/ara_default.py", line 498, in _get_or_create_host
    self.host_cache[host] = self.client.post("/api/v1/hosts", name=host, playbook=self.playbook["id"])
```

I did verify the credentials used for this account and they work:
```
jeff@carrier:~$ curl -v https://monitoring.zm1.element-networks.nl/zabbix/ -u zabbix-cli
Enter host password for user 'zabbix-cli':
*   Trying ipv6:443...
*   Trying 10.1.1.36:443...
* Connected to monitoring.zm1.element-networks.nl (10.1.1.36) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: O=ELEMENT-NETWORKS.NL; CN=monitoring.zm1.element-networks.nl
*  start date: Feb 11 20:32:18 2023 GMT
*  expire date: Feb 11 20:32:18 2025 GMT
*  subjectAltName: host "monitoring.zm1.element-networks.nl" matched cert's "monitoring.zm1.element-networks.nl"
*  issuer: O=ELEMENT-NETWORKS.NL; CN=Certificate Authority
*  SSL certificate verify ok.
* Server auth using Basic with user 'zabbix-cli'
> GET /zabbix/ HTTP/1.1
> Host: monitoring.zm1.element-networks.nl
> Authorization: Basic blabla==
> User-Agent: curl/7.74.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Tue, 16 May 2023 09:03:35 GMT
< Server: Apache/2.4.56 (Debian) mod_auth_gssapi/1.6.3 OpenSSL/1.1.1n
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Location: index_http.php
< Set-Cookie: zbx_session=eyJzZXNzaW9uaWQiOiJlMGQyMDY2Zjc5NDNkZmVkMTQ4ODBhZjdlZWEzNWVmMSIsInNpZ24iOiI3NzQ4ODMxYzRiMGNhZTA3MTg5YjM4NDY1N2JjNDE4MDM3NDQ0Nzk3ODQ4ZjZmNjA5MDcyNmE1MTgwMGJiYjE5In0%3D; path=/zabbix; secure; HttpOnly
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< 
* Connection #0 to host monitoring.zm1.element-networks.nl left intact
```

**Comment by BGmot** [comment]
I don't see where you provide `zabbix_api_http_user` and `zabbix_api_http_password` variables that are used to do Basic authentication.

**Comment by Thulium-Drake** [comment]
Ah, I missed that, it's only mentioned in the README and not in the ```defaults/main.yml```, I copied the variables from there.

Anyway, I updated my config, works like a charm! Thanks for the quick reply! :-)
